'use client'

import { useProjectStore } from '@/lib/state/project-store'

export function ReportPreview() {
  const { fileName, layers, pageCount } = useProjectStore()
  const totalCount = layers.reduce((sum, l) => sum + l.count, 0)
  const generatedAt = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  return (
    <div className="bg-white shadow-xl rounded-sm p-10 min-h-[842px] flex flex-col gap-6 max-w-[595px] w-full">
      <div className="flex justify-between items-start border-b-4 border-primary pb-6">
        <div>
          <h2 className="text-xl font-bold text-on-surface uppercase tracking-tight">Layer Analysis Report</h2>
          <p className="text-xs text-on-surface-variant mt-1">{fileName}</p>
        </div>
        <div className="text-right">
          <p className="font-bold text-primary text-sm">Counter-Slice</p>
          <p className="text-xs text-on-surface-variant">{generatedAt}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'Total Layers', value: layers.length },
          { label: 'Total Objects', value: totalCount.toLocaleString() },
          { label: 'PDF Pages', value: pageCount },
        ].map((stat) => (
          <div key={stat.label} className="bg-surface-container-low rounded-lg p-3 text-center">
            <p className="text-2xl font-bold text-primary">{stat.value}</p>
            <p className="text-xs text-on-surface-variant mt-1">{stat.label}</p>
          </div>
        ))}
      </div>

      <div>
        <h3 className="text-base font-semibold text-on-surface border-b border-outline-variant pb-2 mb-3">
          Executive Summary
        </h3>
        <p className="text-sm text-on-surface-variant">
          This report summarizes the PDF layer analysis for <strong>{fileName}</strong>.{' '}
          {layers.length} layer{layers.length !== 1 ? 's' : ''} were detected and analyzed,
          containing a total of {totalCount.toLocaleString()} objects across {pageCount}{' '}
          page{pageCount !== 1 ? 's' : ''}.
        </p>
      </div>

      <div>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-surface-container-low">
              {['Layer Name', 'Source', 'Objects'].map((h) => (
                <th key={h} className="py-2 px-3 text-xs uppercase text-on-surface-variant font-bold border-b border-outline-variant">
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="text-sm">
            {layers.map((layer) => (
              <tr key={layer.id} className="border-b border-outline-variant">
                <td className="py-2 px-3 font-medium">
                  <span className="inline-flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: layer.color }} />
                    {layer.name}
                  </span>
                </td>
                <td className="py-2 px-3">
                  <span className="text-xs bg-surface-container px-2 py-0.5 rounded-full text-on-surface-variant">
                    {layer.source === 'ocg' ? 'OCG' : 'Zone'}
                  </span>
                </td>
                <td className="py-2 px-3 font-semibold text-primary text-right">
                  {layer.count.toLocaleString()}
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={2} className="py-2 px-3 font-bold text-sm">Total</td>
              <td className="py-2 px-3 text-right font-bold text-primary">{totalCount.toLocaleString()}</td>
            </tr>
          </tfoot>
        </table>
      </div>

      <div className="mt-auto pt-6 text-center border-t border-outline-variant">
        <p className="text-xs text-on-surface-variant">Generated by Counter-Slice — PDF OCG Layer Counter</p>
      </div>
    </div>
  )
}
